# Generated by Django 3.1.1 on 2020-11-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('suggestion', models.TextField(blank=True, null=True)),
                ('rating', models.CharField(choices=[('1', 'o'), ('2', 'tw'), ('3', 'th'), ('4', 'fo'), ('5', 'fi'), ('6', 'si'), ('7', 'se'), ('8', 'e'), ('9', 'n'), ('10', 'te')], max_length=2)),
            ],
        ),
    ]
